### PR TITLE
VPN example

### PR DESCRIPTION
**Pull request by alex-eri**

### CODE REVIEW

**Comment by jlaine** [comment]
Isn't there some library we can leverage to keep the tun/tap code to a minimum?

One candidate:

https://pypi.org/project/pytap2/

**Comment by alex-eri** [comment]
I did not found ideal "pytap".
Your candidate has

        ret = os.system(ifconfig_cmd)

so i cant run as non root user.

**Comment by alex-eri** [comment]
vpn blocks after 8 megabit/s =)

**Comment by jlaine** [comment]
Unrelated but I'd love your input: I don't like having to copy around the signaling.py in every example, yet it doesn't feel as though it should live in the aiortc library itself. Any suggestions?

My local version of it has additional signaling methods like a Unix socket for local testing

**Comment by alex-eri** [comment]
It posible to send answer before reading offer?

For example.
I want signaling with HTTP POST or PUT with local description as payload returning remote.
Offerer puts desc, server blocks until Answerer puts desc, then server returns answer to offerer and offer to asnswerer.

**Comment by alex-eri** [comment]
Why do you use lists instead of [Queue](https://docs.python.org/3/library/queue.html#queue.Queue) or [asyncio.Queue](https://docs.python.org/3/library/asyncio-queue.html#asyncio.Queue)?

**Comment by jlaine** [comment]
OK let's stay focused on the VPN example in this ticket, and open other issues for the signaling

**Pull request merged**
